### ISSUE TITLE
incorrect baking

### ISSUE THREAD

**Issue by soundsbeard** [richardlayman/udim_bake#1]
hi

i've got 4 udims, 8k each, normal maps, 16bit
blender-3.1.2-linux-x64

this is render with manual baked normals:

![Andy Samberg_043](https://user-images.githubusercontent.com/16347074/168891714-f61e8e3b-c515-4220-a520-0af11a1f5799.png)

and this via addon:

![Andy Samberg_044](https://user-images.githubusercontent.com/16347074/168891758-51f351c0-b471-4a8a-916b-9990a71bfcb4.png)

here is info of manual baked image got with imagemagic (if it helps):
https://pastebin.com/41jsdMkm

and info of addon baked map:
https://pastebin.com/VaswixGL

both normal maps are in this zip:
https://sam.nl.tab.digital/s/TRzp8tJcbJwdTfL

cheers.

**Comment by richardlayman** [comment]
Sorry about the late response, GitHub never notifies me for some reason.

Is it possible to get the scene file from you so I can see the issue. I know that this might not be possible since scene files are usually private and people don't want them to get out there, so it's no problem if you can't.

Also, could you check to see if Blender reset the image files Color Space to RGB instead of Non Color.

If they are all set to Non Color, then could you tell me how this is being baked manually.
Are you baking from a MutiRes or two separate objects?
If you are baking from two objects, what is your Extrusion and Max Ray Distance set to?

**Comment by soundsbeard** [comment]
here is bake scene: https://sam.nl.tab.digital/s/qnwMeRzertkBibz

i always double check that image is baking in non-color space. and now i rebaked once more to make sure its always non-color.

manual baking is 'selected to active', 1 render sample, extrusion 0.001 m, max ray distance 0, scene units are correct.

**Comment by richardlayman** [comment]
Ok, thanks for the file. I'm pretty sure this is happening due to the script not loading the extrusion and ray distance values. I should have a fix soon.

**Comment by richardlayman** [comment]
I've pushed what I believe to be a fix for this. I could not verify this because the scene that you sent me baked both files the same for me both before and after the changes. I've also made it so the script will see the the use_cage option as well. Let me know if this fixes your issue.

**Comment by soundsbeard** [comment]
ok, so

- i've deactivated old addon
- removed old addon
- installed new version

8 bit images are baked correctly 
16 bit images still look weird

btw, i'd also like to mention that image on the main github page is somewhat incorrect.
i mean baked normal map of a cube. the background of numbers should be flat color, like this: 
![tsfc1VI](https://user-images.githubusercontent.com/16347074/170354967-622e7ff3-827a-43fc-941c-16ffb4529033.png)

**Comment by richardlayman** [comment]
The reason I didn't see your issue before was because I was baking using 8bit images, once I switched over to 16 bit images I saw the issue.
The problem was that, for some reason, the image mode was getting switched out of non-color during the bake process. I made it so that all the image's mode was set to non-color before the baking process and everything baked fine. I've pushed the fix, if this fixes your issue, let me know so I can tag and release it.

With the issue of the image on the GitHub page. The reason it looks like that is because the cubes were set to smooth shading instead of flat. I did that on purpose because the number were sculpted and I wanted to smooth out the polygon faces. I thought this might cause some confusion with some people and I may add another image in the future with a flat example to clear things up.

**Comment by soundsbeard** [comment]
ok, so i've checked 16bit with both 1k and 8k resolution, everything seems fine.
thank you very much for your work!
issue can be closed

**Comment by richardlayman** [comment]
Sounds good. I've made one more change. The last version you downloaded manually sets the color-mode to non-color for all baked images. This is fine for normal maps but would cause issues for other bakes. I've updated the script so that now the color-mode is based off the source image so that all bakes will have the proper color-mode set. If all you're baking is normal maps, you don't need to update.
